---
sudo: required
services:
  - docker

branches:
  only:
    - master

env:
  global:
    # DOCKER_EMAIL
    - secure: "qeiM+fd7IGy8cCp93WXeyUz+0BSysKlDnFAmi7vuy6c4Uy8WX464CTWidfgbtXv/38mQb1elhWhDb/ztB+QQE3v1ndhv3NluGLXPJmjDl+wzFFRMbksenO66qogIuzsvUb+fR1Kn7fmg+vSa8l/4aWkRCeugbD2IsWP+5USyoUrUNPGaGTbCCwE5+EEUPWviHl/9/mO9Yh2GvdY3QUgsq8Pc5fJvUAJwPcsUimc/zjuensi3iF6iglplEJprXwKegrXo4ocNzZBDZkEHtZbsM407DFx8k1svGBkcjyxWxKeQneTxhe2cMcr/SDBOiV6GaZYAi1MFuY7F+54GzHK14wI1bha2A0x0bgO4UiVQl7h4ZZRbsHbSXkIL9OZ3KZTAAnYFOu5/6PJ7+b3YUQGloPREQoCxptufBvM4eeSPgVFCNQ4mEe7nqlguTAKLcl4Ho4OjtrT0uCpNduSB3dY8I+QzB8v9daRjLctC8NgKLWU/5kVI23aGNSEHu5O5Q1SDW0oRKfX8R0yvgSkPCLx/mUQ7c8Dgifr3Tdn1Lb1nQ2rSUPVeH165zSsOOjq4FYJOSazEmJEmuC2tyU0RnlCzXF4lPLnXh7czBwYIlXrEjbH370BD+C23fnlX47rr7cWlwhPiIz6QKi6dzEMJyyJV9sI2LrnGAgQPah/OUnb/0AI="
    # DOCKER_USER
    - secure: "GyLALioU32+BXW98RO/Ab9D4/86OPb5qsAYCpJUuVeMuiJbp4QeTu/W7L4hUrpvaZ0vTv4k9xCbRvhKg3WkcqzR8qqw85cQQ2GcfSfs2caVKmu8Wu/8sQytweEqIhIJ7nxyJdZzvM0xlosPLqGjGOhTn3wsAnm8AJcPuTWG8wEeJjMXp1KGA4cnN4ViYPCN3jnuXy7aGjICb1jgmY2uNLNx5EQ++9wWNa9O4is48VE7ieHVAzY19aoP/aVfGKTTUf63blmTlqypUAzhikAW68tHZaZDqiYu2UnlDQod42gEpn/16pdQPzW4qrinJ8h5w7qTm6HAtfSMHg1vFI0JFS8x3MIGDQHHHIX6CkMqpST0/4Dx1IJlggOrdr6NXiY1Z/wy9b+FcnfCwpUqu13raEtnU1f40bOzsCMRKPrgOe4OUKMWpr4wOzFAe/s9HOOl2IOumUAsdRJB/5bW4jcDSOEijIig9l1937yNaJYlWSrYvo2elJ/IgROMNwpqgviwLqJqDeJJaafkyPTlKntfhdIocYvbtgw/BDnL45udUznJUijQpFHW3YYU5PCGLMjnykwHHE/DBhrEG/gEQIQMSQMPRUeW6Ux3jtMFsVVU3eamCXhnKaopIzpi3f/Yl2nwcivE3bh1fHA1yzCl2sFufJ/8VdWfuwUPtoGwMUgN3jl4="
    # DOCKER_PASS
    - secure: "RL2nikOzanOA4Y4DAeEurJBYwRto/SumvqT7/M44r/09Mi+lo2fs6/fVuzaiwQWTUNa4735HvDOou5J1XTushE8RcYj1ifIyLTNuReuhX3LxoaxbCk3+o/9oHtmpAEKa2p2aSGcwdlCKr6LdwqJTVqin+VhYIpL3rNCNksX72kBemHB4y89g7BBYyuMSflY+1aZwgHO1NyvV5Sjx2+II1D/ij3fPcu+awhU/AhR2ouO4UpT0UHQ3GrLRzSbOAE4hZbCcxd0Cj35B4iRTLgJDBbxKzpV3XUf8klsEWBXsMFsOgFKmxNSJiscdaijMS4nBsRjZArc89MU5a1NvTbxokZD50BxakoryZsSoazvtpYnH99mDJ0KN9HauYXaVB9M1BfmxISqMicdyu5ET7faB1eJ4qIJCyWvo0vQx7apZi0N+dykeu6MRKVJapwqT8UlW2U+hGMntXmCq2RYaKBkAVOtc7fTBvArA2V84saF0d22NKioiXAemXMIvw2ceQ9o3t4iXwnIwBJCE4oCktzhLEDocfidh02CpdGv0RMZe4JDlwVNj/y3scc5OKIEhF9nikVgusqNYKoVYv0XBE+SBf9EHSW87iLS4SNenM3wGWmgmkMMMDtf4v7cmdYmY3zyljm2VGKtAzqErCfyZ/G9PnBCzHcHd7dSwxFwrWoJ2rMA="
    - DOCKER_REPO=spreadspace/onionbalance

script:
  ### build the new images
  - docker build -t $DOCKER_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER .

after_success:
  - >-
    if [ "${TRAVIS_BRANCH}" = master ]; then
      DOCKER_TAG="latest"
    else
      DOCKER_TAG="${TRAVIS_BRANCH}"
    fi
  - docker tag $DOCKER_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$DOCKER_TAG
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:$DOCKER_TAG
